### PR TITLE
Fix import bug in Transmission.py

### PR DESCRIPTION
**Pull request by sachk**

### CODE REVIEW

**Comment by kannibalox** [comment]
Thanks!

**Comment by sachk** [comment]
I found another bug with transmission, but I did a quick fix that might've broken rtorrent support. I'll make another pull request with it once I neaten it up. Also, I've figured out how to run it in a Docker container with user support, so I'll neaten that up and publish a container soon.

**Comment by sachk** [comment]
Upon adding the torrent to transmission after it's been uploaded, this branch currently will add the torrent a folder further into the tree then it should be. This is because of this line added during the change to mktor.

```python
                        return os.path.join( path, self.ReleaseName )
```

So, I added this horribly named function
```python
        def GetBaseReleaseUploadPath(self):
                return os.path.join( self.GetReleaseRootPath(), "upload" )
```

and changed the StartTorrent def to point at it

```python        
      def __StartTorrent(self):
                if len( self.ReleaseInfo.UploadTorrentInfoHash ) > 0:
                        self.ReleaseInfo.Logger.info( "Upload torrent info hash is set, not starting torrent again." )
                        return
               # Add torrent without hash checking.
                self.ReleaseInfo.UploadTorrentInfoHash = self.TorrentClient.AddTorrentSkipHashCheck( self.ReleaseInfo.Logger,
                self.ReleaseInfo.UploadTorrentFilePath, self.ReleaseInfoGetBaseReleaseUploadPath() )
                Database.DbSession.commit()
```

This works for transmission, but I'm not sure if it works for rtorrent so someone else will have to test that.

It'd be better to handle this differently, so I'll leave that to you or someone else who knows the code base better.

**Comment by sachk** [comment]
@kannibalox this seems to still be a problem in develop.

**Pull request merged**
